### ISSUE TITLE
Pairing handling

### ISSUE THREAD

**Issue by bitgamma** [luibo/KeycardForiPhone#1]
Hi,

First of all, nice project!

I have been checking the code and the "encountered issues" section of you very detailed documentation! I have noticed there that the biggest problem you encountered with pairing comes from a misunderstanding of how pairing works. You are not  supposed to pair/unpair on each interaction. The demo code we have do it this way because they are a "one-shot" thing, but in a real app you are supposed to only pair once and save the pairing itself (ie: the Pairing object inside the command set) instead of the pairing password.

Unpairing, if provided, should be an explicit function that the user can invoke when they don't want to use the card with the app anymore.

**Comment by luibo** [comment]
Hi Bitgamma,

I'm happy that you liked my project, I actually put a lot of effort on it.
I think Keycard has a lot of potential use cases, and I'm currently working
even on an integration with MetaMask in order to make mobile devices
compatible with hardware wallets.

Regarding Keycard for iPhone, first of all I'm sorry if the code you read
is not the most beautiful; I didn't have much time for completing the
project, and this resulted in a not very well-written code. The first thing
I'm planning to do for the project is a code refactoring to make it more
readable and clean.

Talking about the pairing issue, the problem is that I had a different
concept about the real app usage: rather than automatically pairing and
giving users the possibility to unpair the card, I thought to give the user
the possibility to pair the card with a device only if he wants; this
concept derives from a use case where a device with the app is used by a
vendor in a commercial context: for example, the vendor generates the
purchase transaction and lets the customer sign it with Keycard through his
device (what I was thinking of is a scenario similar to standard credit
card contactless payments). So, in this case the user could prefer not to
pair his card with an unknown device. Obviously this is just a concept, I
could change the way the app works in something more user-friendly, even
though I think this use case should be considered in some way.

Finally, in the documentation I said that badly when I talked about bug
fixing in the SDK. Actually I did not made real bug fixes, I just changed
some functions declarations as, in the way they were written, it was not
possible to use them as shown in the SDK documentation (for each function I
referred to the documentation of the Java SDK for Android); most of these
fixes consisted in adding the "public" keyword before "static" in some
functions declarations, with this small fix it was possible to use them in
the same way they're used in the Java version. I can still make a PR if you
think these are relevant changes.

If you're interested in the project don't hesitate to contact me, I'll be
glad to provide any information about the development.

Regards.

L.B.

Il giorno mar 7 lug 2020 alle ore 08:05 Bitgamma <notifications@github.com>
ha scritto:

**Comment by bitgamma** [comment]
The scenario you are describing (credit card) is supported by Keycard in two ways:

- The Keycard cash applet which allows PIN-less, securechannel-less one-tap signature (with a different key from the hardware wallet, with said key being just the signer for a smartcontract for example)
- The pinless path. Similarly the main Keycard applet supports securechannel less/PINless signing if setting the pinless path.

The first feature is supported since Keycard 3.0 and the second one since Keycard 2.2

Pairing the card requires a pairing password so it is not really suited for tapping on 3rd party devices. Also, unless the devices are some sort of certified/trusted devices (like POS), entering the PIN actually exposes the user more than using the pinless path (since it can be logged and can be used to do anything on the card).

Pairing is relatively expensive and writes to NVM, so continued usage will also eventually wear the card's EEPROM. It is really not meant for ephemeral connections.

Regarding your changes to the SDK, even if they are minor ones please submit a PR so we can integrate them.
